/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CheckboxGroup: typeof import('primevue/checkboxgroup')['default']
    Column: typeof import('primevue/column')['default']
    ColumnItemSlot: typeof import('./src/components/column-item-slot.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogContentSlot: typeof import('./src/components/dialog-content-slot.vue')['default']
    DialogRender: typeof import('./src/components/DialogRender.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Fluid: typeof import('primevue/fluid')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    FormItemSlot: typeof import('./src/components/form-item-slot.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LayoutDetail: typeof import('./src/components/layout-detail.vue')['default']
    LayoutDetailDescriptions: typeof import('./src/components/layout-detail-descriptions.vue')['default']
    LayoutDialog: typeof import('./src/components/layout-dialog.vue')['default']
    LayoutFilter: typeof import('./src/components/layout-filter.vue')['default']
    LayoutForm: typeof import('./src/components/layout-form.vue')['default']
    LayoutFormItem: typeof import('./src/components/layout-form-item.vue')['default']
    LayoutMessage: typeof import('./src/components/layout-message.vue')['default']
    LayoutTable: typeof import('./src/components/layout-table.vue')['default']
    LayoutTablebar: typeof import('./src/components/layout-tablebar.vue')['default']
    LayoutTableColumnSolt: typeof import('./src/components/layout-table-column-solt.vue')['default']
    LayoutToolbar: typeof import('./src/components/layout-toolbar.vue')['default']
    LayoutTreetable: typeof import('./src/components/layout-treetable.vue')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PageRender: typeof import('./src/components/PageRender.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RadioButtonGroup: typeof import('primevue/radiobuttongroup')['default']
    Select: typeof import('primevue/select')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TreeSelect: typeof import('primevue/treeselect')['default']
    TreeTable: typeof import('primevue/treetable')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}

// For TSX support
declare global {
  const Button: typeof import('primevue/button')['default']
  const ButtonGroup: typeof import('primevue/buttongroup')['default']
  const Checkbox: typeof import('primevue/checkbox')['default']
  const CheckboxGroup: typeof import('primevue/checkboxgroup')['default']
  const Column: typeof import('primevue/column')['default']
  const ColumnItemSlot: typeof import('./src/components/column-item-slot.vue')['default']
  const ConfirmDialog: typeof import('primevue/confirmdialog')['default']
  const DataTable: typeof import('primevue/datatable')['default']
  const DatePicker: typeof import('primevue/datepicker')['default']
  const Dialog: typeof import('primevue/dialog')['default']
  const DialogContentSlot: typeof import('./src/components/dialog-content-slot.vue')['default']
  const DialogRender: typeof import('./src/components/DialogRender.vue')['default']
  const FloatLabel: typeof import('primevue/floatlabel')['default']
  const Fluid: typeof import('primevue/fluid')['default']
  const FormField: typeof import('@primevue/forms/formfield')['default']
  const FormItemSlot: typeof import('./src/components/form-item-slot.vue')['default']
  const InputNumber: typeof import('primevue/inputnumber')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const LayoutDetail: typeof import('./src/components/layout-detail.vue')['default']
  const LayoutDetailDescriptions: typeof import('./src/components/layout-detail-descriptions.vue')['default']
  const LayoutDialog: typeof import('./src/components/layout-dialog.vue')['default']
  const LayoutFilter: typeof import('./src/components/layout-filter.vue')['default']
  const LayoutForm: typeof import('./src/components/layout-form.vue')['default']
  const LayoutFormItem: typeof import('./src/components/layout-form-item.vue')['default']
  const LayoutMessage: typeof import('./src/components/layout-message.vue')['default']
  const LayoutTable: typeof import('./src/components/layout-table.vue')['default']
  const LayoutTablebar: typeof import('./src/components/layout-tablebar.vue')['default']
  const LayoutTableColumnSolt: typeof import('./src/components/layout-table-column-solt.vue')['default']
  const LayoutToolbar: typeof import('./src/components/layout-toolbar.vue')['default']
  const LayoutTreetable: typeof import('./src/components/layout-treetable.vue')['default']
  const Message: typeof import('primevue/message')['default']
  const MultiSelect: typeof import('primevue/multiselect')['default']
  const PageRender: typeof import('./src/components/PageRender.vue')['default']
  const Paginator: typeof import('primevue/paginator')['default']
  const Password: typeof import('primevue/password')['default']
  const ProgressSpinner: typeof import('primevue/progressspinner')['default']
  const RadioButton: typeof import('primevue/radiobutton')['default']
  const RadioButtonGroup: typeof import('primevue/radiobuttongroup')['default']
  const Select: typeof import('primevue/select')['default']
  const Textarea: typeof import('primevue/textarea')['default']
  const Toast: typeof import('primevue/toast')['default']
  const ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  const TreeSelect: typeof import('primevue/treeselect')['default']
  const TreeTable: typeof import('primevue/treetable')['default']
}